### ISSUE TITLE
is setState necessary in the updateValue Callback?

### ISSUE THREAD

**Issue by spirobel** [onikienko/use-chrome-storage#174]
is this line necessary?
https://github.com/onikienko/use-chrome-storage/blob/57c5c80e1c3e023049f565a6bd1630f527692221/src/useChromeStorage.js#L36

I thought setState will be triggered here through the onchange event:
https://github.com/onikienko/use-chrome-storage/blob/57c5c80e1c3e023049f565a6bd1630f527692221/src/useChromeStorage.js#L51

Great Work by the way!

Regards,
Spriobel

**Comment by onikienko** [comment]
Hi @spirobel 

Looks like you are right. It's not required. Will need to check and fix it. Thank you!
