### ISSUE TITLE
Typescript error - must have a '[Symbol.iterator]()' method that returns an iterator.

### ISSUE THREAD

**Issue by pauloendoh** [onikienko/use-chrome-storage#342]
The following code show this typescript error: 

Type '() => [number, Dispatch<SetStateAction<number>>, boolean, string]' must have a '[Symbol.iterator]()' method that returns an iterator.

```typescript
 const [value, setValue, isPersistent, error] = useChromeStorageLocal(
    'counterLocal',
    0
  )
```

If I put a @ts-expect-error before the line, it runs ok, but the values won't be typed.

**Comment by onikienko** [comment]
Thank you for reporting @pauloendoh 
The community supports typing.  Typescript is not my language. 
It will be great if you create PR with a fix.

**Comment by vinicoder** [comment]
Hey, guys! @onikienko @pauloendoh I made this PR to fix it. Can you review it? I would love to use this library, and this is the only thing missing from me. https://github.com/onikienko/use-chrome-storage/pull/349
