### ISSUE TITLE
`createChromeStorageStateHookLocal` knowing when value has been fetched (or none found in storage)

### ISSUE THREAD

**Issue by spencerc99** [onikienko/use-chrome-storage#346]
hi there! thanks for making the library :) I'm trying to leverage local chrome storage to 1) persist some remote data that is fetched and 2) annotate that remote data based on actions done via the chrome extension.

I'm running into some issues with this because all of the data I annotate is blown away whenever I fetch from the remote data (even though I check if the existing store has the annotated data). The issue is that there's no way for me to know whether the value that the hook returns is the `initialValue` because it has not yet been loaded or if it's because it has no information about it.  I wonder if there's any way to return another boolean from the hook to indicate `hasLoaded` where it would be false until successfully loaded from local storage.

Open to ideas of other ways to solve this as well.

**Comment by onikienko** [comment]
It sounds like you need to `useEffect` to react on your data changes. Something like that:

```javaScript
// init 
const useCounterStore = createChromeStorageStateHookLocal('myCounter',  0);

// somewhere in the component
const [counter, setCounter] = useCounterStore();

React.useEffect(() => {
    // will fire only when couner changed
}, [counter]);
```

Be careful if your data is not primitive (array or object).  In this case, you will need to avoid running this effect on each component update.

**Comment by spencerc99** [comment]
> It sounds like you need to `useEffect` to react on your data changes. Something like that:
> 
> ```js
> // init 
> const useCounterStore = createChromeStorageStateHookLocal('myCounter',  0);
> 
> // somewhere in the component
> const [counter, setCounter] = useCounterStore();
> 
> React.useEffect(() => {
>     // will fire only when couner changed
> }, [counter]);
> ```
> 
> Be careful if your data is not primitive (array or object). In this case, you will need to avoid running this effect on each component update.


Hmmm I'm already using a `useEffect` and its getting run when `counter` is still the default value

**Comment by onikienko** [comment]
It's how things work in React. `useEffect` always fires on the initial render. Intentionally.

![image](https://user-images.githubusercontent.com/3234928/221520905-a8fad1ac-51a6-4198-a639-8350b26a927d.png)
[docs](https://reactjs.org/docs/hooks-effect.html#example-using-hooks)

It's out of `use-chrome-strage` lib topic. But I guess you need to adapt your extension/app logic to be more "react-way".

**Comment by onikienko** [comment]
Regarding your `hasLoaded` proposal. The fact of state change means that data **has loaded**.  
So you just need to `useEffect` which depends on the state and design your components accordingly. Keeping in mind React hooks behavior and logic (initial render, shallow compare of non-primitive dependencies, etc).

**Comment by spencerc99** [comment]
I don't think having a concept of `hasLoaded` is non-reactive. This is a pretty common technique in react to trigger rendering when loading remote data. You have an `isLoading` state value which you default to true and after an async load process (via `useEffect`), you can set that to false. 

The problem is that the state doesn't change if there is no value already set. The default value is loaded as the default value, so I have no way of telling if the value coming from the chrome storage local hook is before it has been loaded or after it has been loaded.

**Comment by spencerc99** [comment]
The other way I can picture achieving this is something like a `whileLoadingValue` that you can specify in addition to `initialValue`. In this case, I might set `whileLoadingValue` to be `null` to know that it is still loading. In fetching from the chrome storage, it would either find a value there, or set it to `initialValue` after it has been loaded.

For example, with a generic async process, this is how I would do that:
```jsx
const [data, setData] = useState<any[] | null>(null);

async function loadData() {
    const resp = await fetch("https://data-url");
    const data = await resp.json();
    setData(data || []);
}

useEffect(() => {
  void loadData();
}, [])

return data === null ? <div>Loading...</div> : <div>{data.map(renderDataItem)}</div>
```

**Comment by onikienko** [comment]
Say we have the next hook:
`const [value, setValue, isPersistent, error] = useChromeStorageLocal('counterLocal', 0);`
In the `chrome.storage.local` we already have: `counterLocal: 10`

Changes of `value`:

0. initial component render
1. `value` is 0 (set via initialValue of the hook)
2. `useChromeStorageLocal` call to chrome API to get the value of `counterLocal`. `value` changes to *10*

Do you need to know when initialValue was replaced with the value stored in the storage (stage 2 in that example)? Something like  `initialStateLoaded`?

**Comment by spencerc99** [comment]
> Do you need to know when initialValue was replaced with the value stored in the storage (stage 2 in that example)? Something like isInitialStateResolved?

Right exactly! The exact situation is because I'm seeding the value from a remote source. So I have some logic later in the file that is something like (in a `useEffect`):
```
// the defaultValue is `null` for ex.
// The problem is that this triggers while the data is loading AND on the initial load when there is nothing in local storage
if (!value) {
  fetchAndSetValue()
}
```

I basically only want that piece of code to run if and only if we have already loaded from local storage, and found that there is nothing there.

**Comment by onikienko** [comment]
Got your point. 
It make sense. 
Will implement

**Comment by spencerc99** [comment]
great thank you :)

**Comment by spencerc99** [comment]
hi! i saw you made the commit on this, just wanted to check in on when you think it'd be ready to merge? I have a project I'm planning on launching this week that relies on this functionality. Want to check if I need to fork to get in time for my deadline!

**Comment by onikienko** [comment]
I plan to release today.

**Comment by spencerc99** [comment]
thanks! I'm testing this now, and it doesn't ever seem to be setting to complete? any ideas what's going on?

<img width="536" alt="image" src="https://user-images.githubusercontent.com/14796580/223296012-c2c45c56-2138-41e6-8073-1bc964a7571a.png">

this is the code
```
export const useReviewItemsStore = createChromeStorageStateHookLocal<
  ReviewItem[]
>(StorageReviewItemsKey, []);
  const [
    reviewItems,
    setReviewItems,
    _persistent,
    _err,
    isInitialStateResolved,
  ] = useReviewItemsStore();
  console.log("initial state resolved?", isInitialStateResolved);
```

**Comment by onikienko** [comment]
Right! I forgot about `createHook...`. Will review your PR
