### ISSUE TITLE
value in useEffect is undefined

### ISSUE THREAD

**Issue by botshen** [onikienko/use-chrome-storage#428]
I want to get the value of the chrome-storage when the page is mounted and then display it back on the page, if the chrome-storage is not there then set the default value, but in useEffect my projectList is undefined, how to solve it?

"The second argument of useChromeStorageLocal does not initialize values in Chrome storage, What does the second parameter do?

```jsx
import { useChromeStorageLocal } from 'use-chrome-storage';

 const [projectList, setProjectList] = 
useChromeStorageLocal(AJAX_INTERCEPTOR_PROJECTS, [{ "pathUrl": "localhost:3000", "rules": [] }]);
 const [currentProject, setCurrentProject] =
 useChromeStorageLocal(AJAX_INTERCEPTOR_CURRENT_PROJECT, "localhost:3000");

  useEffect(() => {
    console.log('projectList', projectList)// this is undifined

    if (!projectList || !projectList.length) { 
      const defaultProjectProduct = {
        pathUrl: 'localhost:3000',
        rules: []
      }

      setProjectList(() => {
        return [defaultProjectProduct]
      })

      setCurrentProject(() => defaultProjectProduct.pathUrl)
     }
  
  }, []);
```

**Comment by onikienko** [comment]
The second parameter is `initialValue` - the value used if `chrome.storage.local` has no stored value yet. And it works as expected. 

For your code. It is hard to say from where the error is coming. The first thing to check is the dependencies array in your `useEffect` hook. It's empty but depends on state changes. And the whole hook looks strange.

**Comment by botshen** [comment]
What I'm trying to do is get the value inside the stroge when the component is first rendered, and if it doesn't have it, set it, and if it does have it, use it.

**Comment by botshen** [comment]
Thank you for your answer, your code works, the reason for this is that my data needs to be stored in the local, if there is no value at the beginning, I want to give the user a default value as a reference, nothing will make the user feel overwhelmed, after submitting this issue I wrote a method to achieve the functionality that I want, but did not use your library, I will consider better use of yours to I will consider using your library better to increase my efficiency!
this is my code:
```tsx
export function getOrCreateLocalStorageValues(keyValueMap: KeyValueMap, callback: CallbackType) {
  // 尝试从chrome.storage.local中获取指定键的值
  chrome.storage.local.get(Object.keys(keyValueMap), function (result) {
    if (chrome.runtime.lastError) {
      // 发生错误
      console.error(chrome.runtime.lastError);
      callback(keyValueMap); // 返回初始值映射对象
    } else {
      const updatedValues: KeyValueMap = {};

      // 遍历键值映射对象，检查每个键的值是否存在
      for (var key in keyValueMap) {
        if (key in result) {
          // 如果存在，将其添加到更新后的值映射对象中
          updatedValues[key] = result[key];
        } else {
          // 如果不存在，将初始值设置到chrome.storage.local中
          updatedValues[key] = keyValueMap[key];
          const data: KeyValueMap = {};
          data[key] = keyValueMap[key];
          chrome.storage.local.set(data, function () {
            if (chrome.runtime.lastError) {
              // 发生错误
              console.error(chrome.runtime.lastError);
            }
          });
        }
      }

      // 返回所有键的最新值映射对象
      callback(updatedValues);
    }
  });
}
```
this is use
```tsx
  useEffect(() => {
    getOrCreateLocalStorageValues({
      [AJAX_INTERCEPTOR_CURRENT_PROJECT]: 'http://localhost:5173',
      [AJAX_INTERCEPTOR_PROJECTS]: [{
        pathUrl: 'http://localhost:5173',
        rules: [{
          name: 'test',
          code: '200',
          switchOn: true,
          delay: '0',
          method: 'POST',
          pathRule: '/api/test',
          Response: {
            code: 200,
            data: {},
            message: 'success'
          },
        }],
        projectName: '默认项目',
        switchOn: true
      }],
      mockPluginSwitchOn: true,
    }, function (values) {
      const checked = values.mockPluginSwitchOn
      setDefaultChecked(checked)
      if (checked) {
        chrome.action.setIcon({ path: '/images/app.png' });
      } else {
        chrome.action.setIcon({ path: '/images/gray.png' });
      }
      setItems(values[AJAX_INTERCEPTOR_PROJECTS].map((item: any) => {
        return {
          key: item.pathUrl,
          label: item.projectName,
          children: <Table
            columns={columns}
            size='small'
            dataSource={item.rules} />,
        }
      }))
      setDefaultActiveKey(() => values[AJAX_INTERCEPTOR_CURRENT_PROJECT])
      setPreviousActiveKey(() => values[AJAX_INTERCEPTOR_CURRENT_PROJECT])

    })
  }, [])
```

**Comment by onikienko** [comment]
> I want to give the user a default value as a reference, nothing will make the user feel overwhelmed

Exactly. But there is no need to store this default value in storage. It will be used from your code. 
Anyway.

**Comment by botshen** [comment]
My other components depend on stroage, and if I just use the defaults here and don't put them in stroage, my other logic reading stroage won't be able to read them, and the plugin won't work properly, which is why I need to put the defaults into stroage

**Comment by onikienko** [comment]
I see. Good to know such a case. In my code, I usually have constants with default values which I import in components where required. 
Anyway. I got your point. Thank you for the explanation.
